server.servlet.context-path: /api
server:
  port: 8888
spring:
  redis:
    timeout: 1000
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 300
        max-wait: -1
        min-idle: 20
        max-idle: 100

    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mb
    password: 1123
    url: jdbc:mysql://papawq.xyz:3306/reddot?allowPublicKeyRetrieval=true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

