server:
  port: 80
spring:
  redis:
    timeout: 1000
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 300
        max-wait: -1
        min-idle: 20
        max-idle: 100

    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/reddotbus

mybatis:
  configuration:
    map-underscore-to-camel-case: true

