server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/reddotbus

mybatis:
  configuration:
    map-underscore-to-camel-case: true
